name: Agent Build CI

on:
  push:
    paths:
      - 'AlcorControlAgent/**'
      - '!AlcorControlAgent/docs/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build Alcor Control Agent
      run: ./build/aca_build.sh
      working-directory: .
