name: Controller Maven CI

on:
  push:
    paths:
      - '**'
      - '!Monitoring/**'
      - '!Plugins/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file AlcorController/pom.xml
